accounts/urls.py
"""accounts用のURLパターンの定義"""

from django.urls import path, include

from . import views

app_name = 'accounts'
urlpatterns = [
    # デフォルトの認証URLを取り組む
    path('', include('django.contrib.auth.urls')),
    # User登録page
    path('register/', views.register, name='register'),
]

learning_logs/urls.py
"""learning_logsのURLパターンの定義"""

from django.urls import path

from . import views

app_name = 'learning_logs'
urlpatterns = [
    # HomePage
    path('', views.index, name='index'),
    # 全てのTopicを表示するpage
    path('topics/', views.topics, name='topics'),
    # 全てのTopicを表示するpage
    path('topics/<int:topic_id>', views.topic, name='topic'),
    # 新規Topicの追加page
    path('new_topic/', views.new_topic, name='new_topic'),
    # 新規記事の追加page
    path('new_entry/<int:topic_id>/', views.new_entry, name='new_entry'),
    # 記事の編集page
    path('edit_entry/<int:entry_id>/', views.edit_entry, name='edit_entry'),
]

ll_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('learning_logs.urls')),
]

accounts/models.py
from django.db import models

# Create your models here.

learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User

class Topic(models.Model):
    """Userが学んでいるTopicを表す"""
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        """modelの文字列表現を返す"""
        return self.text
    

class Entry(models.Model):
    """Topicに関して学んだ具体的なこと"""
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        return f"{self.text[:50]}..."

learning_logs/forms.py
from django import forms

from .models import Topic, Entry

class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}



class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm

def register(request):
    """new_user登録"""
    if request.method != 'POST':
        # 空のUser登録Formを表示
        form = UserCreationForm()
    else:
        # 入力済みのFormを処理
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            new_user = form.save()
            # UserをログインさせHomePageにredirect
            login(request, new_user)
            return redirect('learning_logs:index')
        
    # 空または無効のFormを表示
    context = {'form': form}
    return render(request, 'registration/register.html', context)

learning_logs/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http import Http404

from .models import Topic, Entry
from .forms import TopicForm, EntryForm

def index(request):
    """学習ノートのWebPage"""
    return render(request, 'learning_logs/index.html')


@login_required
def topics(request):
    """全てのTopicを表示"""
    topics = Topic.objects.filter(owner=request.user).order_by('date_added')
    context = {'topics': topics}
    return render(request, 'learning_logs/topics.html', context)


@login_required
def topic(request, topic_id):
    """1つのTopicとそれについての全ての記事"""
    topic = Topic.objects.get(id=topic_id)
    # Topicが現在のUserが所持するものであることを確認
    if topic.owner != request.user:
        raise Http404

    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'learning_logs/topic.html', context)


@login_required
def new_topic(request):
    """new_topicを追加"""
    if request.method != 'POST':
        # dataは送信されていないので空のformを生成
        form = TopicForm()
    else:
        # POSTでデータが送信されたので処理
        form = TopicForm(data=request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return redirect('learning_logs:topics')
    
    # 空または無効のフォームを表示
    context = {'form': form}
    return render(request, 'learning_logs/new_topic.html', context)


@login_required
def new_entry(request, topic_id):
    """特定のTopicにnew_pageを追加"""
    topic = Topic.objects.get(id=topic_id)

    if request.method != 'POST':
        # dataが送信されていないので空のForm生成
        form = EntryForm()
    else:
        # POSTでdataが送信されたのでこれを処理
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return redirect('learning_logs:topic', topic_id=topic_id)
        
    # 空または無効のFormを表示
    context = {'topic': topic, 'form': form}
    return render(request, 'learning_logs/new_entry.html', context)


@login_required
def edit_entry(request, entry_id):
    """既存の記事を編集"""
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    if topic.owner != request.user:
        raise Http404

    if request.method != 'POST':
        # 初回request時はあ現在の記事の内容がFormに埋め込まれている
        form = EntryForm(instance=entry)
    else:
        # POSTでdataが送信されたのでこれを処理
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('learning_logs:topic', topic_id=topic.id)
        
    context = {'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'learning_logs/edit_entry.html', context)

learning_logs/templates/learning_logs/base.html
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>学習ノート</title>

  {% load django_bootstrap5 %}
  {% bootstrap_css %}
  {% bootstrap_javascript %}

</head>
<body>

  <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'learning_logs:index' %}" >
        学習ノート
      </a>

      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" 
      data-bs-target="#navbarCollapse" aria-controls="navbarCollapse"
      aria-expanded="false" aria-label="ナビゲーションの切り替え">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav me-auto mb-2 mb-md-0">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'learning_logs:topics' %}">
            Topic一覧</a></li>
      </ul> <!-- navbar左側のリンクリストの終了 -->

      <!-- アカウント関連のリンク -->
      <ul class="navbar-nav ms-auto mb-2 mb-md-0">
        {% if user.is_authenticated %}
          <li class="nav-item">
            <span class="navbar-text me-2">こんにちは{{ user.username }}さん
              </span></li>
        {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:register' %}">
                User登録</a></li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:login' %}">
                ログイン</a></li>
        {% endif %}

      </ul> <!-- アカウント関連のLINKの終了 -->

      {% if user.is_authenticated %}
        <form action="{% url 'accounts:logout' %}" method="post">
          {% csrf_token %}
          <button name="submit" class="btn btn-outline-secondary btn-sm">
              ログアウト</button>
        </form>
      {% endif %}

    </div> <!-- navbarの折り畳み可能なパーツの終了 -->

    </div> <!-- navbarコンテナの終了 -->
  </nav> <!-- navbar全体の終了 -->

  <main class="container">
    <div class="pb-2 mb-2 border-bottom">
      {% block page_header %}{% endblock page_header %}
    </div>
    <div>
      {% block content %}{% endblock content %}
    </div>
  </main>

</body>
</html>

learning_logs/templates/learning_logs/edit_entry.html
{% extends "learning_logs/base.html" %}

{% block content %}

  <p><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p>

  <p>記事を編集:</p>

  <form action="{% url 'learning_logs:edit_entry' entry.id %}" method="post">
    {% csrf_token %}
    {{ form.as_div }}
    <button name="submit">記事を更新</button>
  </form>

{% endblock content %}

learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}

{% block page_header %}
  <div class="p-3 mb-4 bg-light border rounded-3">
    <div class="container-fluid py-4">
      <h1 class="display-3">学んだことを記録しよう</h1>

      <p class="lead">自分だけの学習ノートを作成して、学んだことをいつでも
        振り返れるようにしよう。<br>
        何か新しいことを学んだら、その内容を要約して記事を書こう。</p>

      <a class="btn btn-primary btn-lg mt-1"
      href="{% url 'accounts:register' %}">登録する &raquo;</a>
    </div>
  </div>

{% endblock page_header %}

learning_logs/templates/learning_logs/new_entry.html
{% extends "learning_logs/base.html" %}

{% block content %}

  <p><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p>

  <p>新規記事を追加:</p>
  <form action="{% url 'learning_logs:new_entry' topic.id %}" method="post">
    {% csrf_token %}
    {{ form.as_div }}
    <button name="submit">記事を追加</button>
  </form>

{% endblock content %}

learning_logs/templates/learning_logs/new_topic.html
{% extends "learning_logs/base.html" %}

{% block content %}
  <p>新規Topicを追加:</p>
  <form action="{% url 'learning_logs:new_topic' %}" method="post">
    {% csrf_token %}
    {{ form.as_div }}
    <button name="submit">Topicを追加</button>
  </form>

{% endblock content %}

learning_logs/templates/learning_logs/topic.html
{% extends "learning_logs/base.html" %}

{% block page_header %}
  <h1>{{ topic.text }}</h1>
{% endblock page_header %}

{% block content %}
  <p>
    <a href="{% url 'learning_logs:new_entry' topic.id %}">新しい記事を追加</a>
  </p>

    {% for entry in entries %}
      <div class="card mb-3">
        <!-- カードの見出し。作成日時と編集用のLINKを含む-->
        <h4 class="card-header">
          {{ entry.date_added|date:'Y年m月d日 H:i' }}
          <small><a href="{% url 'learning_logs:edit_entry' entry.id %}">
            記事を編集</a></small>
        </h4>
        <!-- カードの本体。記事の本文を含む -->
        <div class="card-body">{{ entry.text|linebreaks }}</div>
      </div>
    {% empty %}
      <p>Topicはまだ作成されていません。</p>
    {% endfor %}

{% endblock content %}

learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %}

{% block page_header %}
  <h1>Topic一覧</h1>
{% endblock page_header %}

{% block content %}
  <ul class="list-group border-bottom pd-2 mb-4">
    {% for topic in topics %}
      <li class="list-group-item border-0">
        <a href="{% url 'learning_logs:topic' topic.id %}">
          {{ topic.text }}</a>
      </li>
    {% empty %}
      <li class="list-group-item border-0">Topicはまだ作成されていません。</li>
    {% endfor %}
  </ul>

  <a href="{% url 'learning_logs:new_topic' %}">新規Topicを追加</a>

{% endblock content %}